#配置mybatis
mybatis:
  #开启驼峰命名
  configuration:
    map‐underscore‐to‐camel‐case: true
  mapper-locations: classpath:/mybatis/mapper/*.xml
spring:
  mail:
    host: smtp.163.com
    username: tianchao623755@163.com
    password: JULGLOBEBSZAZAZQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mail
    password: mail
    virtual-host: /mail
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail?serverTimezone=GMT%2B8&autoR&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
mail:
  fromMail:
    addr: tianchao623755@163.com
server:
  port: 8080

logging:
  level:
    com:
      tc:
        mapper: debug
