server:
  port: 8080
  servlet:
    context-path: /security-spring-boot
spring:
  application:
    name: security-spring-boot
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    password:
    username: root
    url: jdbc:mysql://localhost:3306/user_db
    driver-class-name: com.mysql.jdbc.Driver